stages:
  - build
  - docker-build
  - unit-test
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle # from https://stackoverflow.com/a/36050711

cache: &global_cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .gradle
    - .npm
  policy: pull-push

build:backend:
  stage: build
  script:
    - ./gradlew assemble
  image: gradle:jre15
  artifacts:
    paths:
      - ./backend/build

build:frontend:
  stage: build
  script:
    - cd frontend
    - npm ci --cache .npm --prefer-offline
    - npm run build
  image: node:lts-alpine
  artifacts:
    paths:
      - ./frontend/build

docker-build:
  stage: docker-build
  needs:
    - build:backend
    - build:frontend
  dependencies:
    - build:backend
    - build:frontend
  script:
    - docker build -t gitlabanalyzer:$CI_COMMIT_REF_SLUG .
  image: docker
  cache: {}

unit-test:backend:
  stage: unit-test
  needs:
    - build:backend
  dependencies:
    - build:backend
  script:
    - ./gradlew test
  image: gradle:jre15
  cache:
    <<: *global_cache
    policy: pull
  artifacts:
    reports:
      junit: backend/build/test-results/test/**/TEST-*.xml

deploy:dev:
  stage: deploy
  needs:
    - docker-build
  script:
    - docker-compose -f docker-compose.yml -f docker-compose.dev.ym -p gitlabanalyzer_dev stop
    - docker-compose -f docker-compose.yml -f docker-compose.dev.ym -p gitlabanalyzer_dev up -d
  cache: {}
  image: docker/compose
  when: manual