stages:
  - build
  - docker-build
  - unit-test
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle # from https://stackoverflow.com/a/36050711

build:backend:
  stage: build
  script:
    - ./gradlew assemble
  image: gradle:jre15
  cache:
    paths:
      - ./backend/build
      - ./.gradle
    policy: push

build:frontend:
  stage: build
  script:
    - cd frontend
    - npm i
    - npm run build
  image: node:lts-alpine
  cache:
    paths:
      - ./frontend/build
      - ./frontend/node_modules
    policy: push

docker-build:
  stage: docker-build
  needs:
    - build:backend
    - build:frontend
  script:
    - docker build -t gitlabanalyzer:$CI_COMMIT_REF_SLUG .
  image: docker
  cache:
    paths:
      - ./backend/build
      - ./.gradle
      - ./frontend/build
      - ./frontend/node_modules
    policy: pull

unit-test:backend:
  stage: unit-test
  needs:
    - build:backend
  script:
    - ./gradlew test
  image: gradle:jre15
  cache:
    paths:
      - ./backend/build
      - ./.gradle
    policy: pull
  artifacts:
    reports:
      junit: backend/build/test-results/test/**/TEST-*.xml


deploy:dev:
  stage: deploy
  needs:
    - docker-build
  script:
    - docker-compose -d
  image: docker/compose
  when: manual