# Based off https://www.baeldung.com/spring-boot-postgresql-docker
version: '2'

services:
  app:
    image: 'gitlabanalyzer'
    build:
      context: .
    container_name: gitlabanalyzer
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/gitlabanalyzer
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gitlabanalyzer