# Based off https://www.baeldung.com/spring-boot-postgresql-docker
version: '2'

services:
  app:
    container_name: gitlabanalyzer_app_dev
    image: 'gitlabanalyzer:${CI_COMMIT_REF_SLUG}'
    ports:
      - 9000:8080
  db:
    container_name: gitlabanalyzer_db_dev
    volumes:
      - /var/lib/docker/volumes/gitlabanalyzer_db_dev:/var/lib/postgresql/data
