# Based off https://www.baeldung.com/spring-boot-postgresql-docker
version: '2'

services:
  app:
    container_name: gitlabanalyzer_app_prod
    image: 'gitlabanalyzer:${CI_COMMIT_REF_SLUG}'
    ports:
      - 80:8080
  db:
    container_name: gitlabanalyzer_db_prod
    volumes:
      - /var/lib/docker/volumes/gitlabanalyzer_db_prod:/var/lib/postgresql/data